name: Update Trackers List

on:
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 hours
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update-trackers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetching tracker lists
        run: |
          echo "Fetching tracker lists from:"
          echo "https://cf.trackerslist.com/all.txt"
          echo "https://cdn.jsdelivr.net/gh/ngosang/trackerslist@master/trackers_all.txt"
          echo "https://cdn.jsdelivr.net/gh/ngosang/trackerslist@master/trackers_all_ip.txt"
          curl -s "https://cf.trackerslist.com/all.txt" -o ./trackers1.txt
          curl -s "https://cdn.jsdelivr.net/gh/ngosang/trackerslist@master/trackers_all.txt" -o ./trackers2.txt
          curl -s "https://cdn.jsdelivr.net/gh/ngosang/trackerslist@master/trackers_all_ip.txt" -o ./trackers3.txt
          cat ./trackers1.txt ./trackers2.txt ./trackers3.txt > ./ultimate_trackers.txt

      - name: Remove duplicates
        run: |
          git clone "https://github.com/FlawlessCasual17/UltimateTrackerList"
          cp ./UltimateTrackerList/scripts/remove-duplicates .
          chmod a+rxw ./remove-duplicates
          bash -c ./remove-duplicates

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add ./ultimate_trackers.txt
          git commit -m "Updated \`ultimate_trackers.txt\`"
          git push origin main
